#pragma once

#include "gdx/XTypes.h"
#include "gdx/XParser.h"
#include "gdx/XBinary.h"
#include "gdx/XSkin.h"
#include "gdx/DDS.h"
#include "gdx/DatLevel.h"
#include "gdx/ElementCatalog.h"
#include "gdx/Xpk.h"
#include "gdx/Game.h"
#include "gdx/Title.h"
#include "gdx/Credits.h"
#include "gdx/D3D8.h"
#include "gdx/D3D8Device.h"
